# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChatApp1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChatApp1
	
	pod 'Firebase'
	pod 'Firebase/Auth'
	pod 'Firebase/Database'
	pod 'lottie-ios'
	pod 'ChameleonFramework'

end
